WITH TRIP AS (

SELECT
RIDE_ID,
--RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE, 
START_STATIO_ID as START_STATION_ID,
END_STATION_NAME as END_STATION_NAME,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

FROM {{ ref('stg_bike') }}


)
select 
* 
from TRIP

